/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _TeoriIdletest_h_
#define _TeoriIdletest_h_
//---------------------------------------------------------------------------------
extern const unsigned char TeoriIdletest[];
extern const int TeoriIdletest_size;
//---------------------------------------------------------------------------------
#endif //_TeoriIdletest_h_
//---------------------------------------------------------------------------------
