/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _TeoriIdle_h_
#define _TeoriIdle_h_
//---------------------------------------------------------------------------------
extern const unsigned char TeoriIdle[];
extern const int TeoriIdle_size;
//---------------------------------------------------------------------------------
#endif //_TeoriIdle_h_
//---------------------------------------------------------------------------------
