/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _stupidRat_h_
#define _stupidRat_h_
//---------------------------------------------------------------------------------
extern const unsigned char stupidRat[];
extern const int stupidRat_size;
//---------------------------------------------------------------------------------
#endif //_stupidRat_h_
//---------------------------------------------------------------------------------
